LanikSJ/dfimage

- README.md
Remove Prerequisites Section of Readme.
Forgot to remove this section in https://github.com/LanikSJ/dfimage/pull/2
Cleaner Readme for all Them Things.
Travis CI
> No Prerequisites Since ECR is Not Used

- .travis.yml
Move Pip Install to Travis Install Section
Cleaning up Travis CI Process.
Faster Travis CI Builds
Travis CI
> Combine All Pip Install Things

- .gitignore
- entrypoint.py
Run entrypoint.py through pylint
https://codecov.io/gh/LanikSJ/dfimage/src/master/entrypoint.py
Improve code coverage
Travis CI and CodeCov
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
> Linting with Pylint

- .travis.yml
Add Codacy Coverage
Codacy Coverage Report doesn't exist
You can never have enough coverage 😎
Travis CI and Codacy
-   [x] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
> Add Codacy Coverage

- README.md
- docs/index.md
Add More Badges and Update Readme
Add Docker Hub Badge and Update README.md
We need more stinking badges!
Travis CI
> Add More Badges and Update Readme

- entrypoint.py
Update Commands and Lint the Code Better
Some of the Commands Were Misspelled
Script Should Follow Better Python Guidelines
Docker & Travis CI
> Renamed Commands and Linting of the Code

- .travis.yml
Update Travis to Fix Pip Issue
#133 
Fix Travis
Travis
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
> Update Travis to Fix Pip Issue

- Dockerfile
Update Alpine to 3.12.0
Docker Alpine Container has been updated
Keep containers up to date
Local & Travis
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
> Update Alpine to 3.12.0

- docs/Gemfile.lock
- docs/assets/main.css
Update GitHub Pages Gems
Code Quality Dropped to a B
Improve Code Quality
Local & Travis
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
> Update GitHub Pages Gems

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Update Docs for Codacy
Codacy Triggers Errors in Markdown
Docs Should Be in Correct Format
GitHub Pages and Codacy
> Update Code of Conduct and Contributing Docs

- entrypoint.py
- requirements.txt
fix this: https://github.com/LanikSJ/dfimage/issues/203
> fix: the right way to use docker client in python

- Dockerfile
Fixes https://github.com/LanikSJ/dfimage/pull/212
> Update Dockerfile To Use Python for Entrypoint

- Dockerfile
- entrypoint.sh
- Let's not use Pipx and add more dependencies and hacky work-arounds
> Use Virtual Environment Instead of Pipx

- .editorconfig
- .github/workflows/dfimage-test.yml
- .github/workflows/docker-publish.yml
- .prettierrc
- Add Editor Config
- Add Prittier Settings
- Add GitHub Actions Exclusions
> Add Editor Prittier and GitHub Actions Excludes

- .github/workflows/dfimage-test.yml
- .github/workflows/docker-publish.yml
- No more Docker Create/Test if the changes don't have:
- `Dockerfile`
- `entrypoint.*`
- `requirements.txt`
> Update GitHub Actions Not To Scan PRs

- .github/workflows/dfimage-test.yml
- .gitignore
- entrypoint.py
Fix for issue #155: FROM attribute in the output Dockerfile is the image itself
> Fix for issue #155

- .github/workflows/dfimage-test.yml
- .github/workflows/docker-hub.yml
- .github/workflows/docker-publish.yml
- Allows to trigger GitHub Actions manually
> Add Manual Trigger to GitHub Actions

- .github/workflows/docker-hub.yml
> Update Docker Hub GitHub Action

- Dockerfile
- Update Dockerfile
- Auto Update Python Packages
> Update Dockerfile and Python Packages

- README.md
- Add Link to Wiki for More Usage Examples
> Update README with Links to Wiki

- README.md
- Remove Extract Instructs Since They're in the Wiki Now
> Remove Extract Instructions

- README.md
- Update badges to latest names, etc
> Update Docker Hub and Publish Badges

- .github/dependabot.yml
- Remove Ignore That's No Longer Necessary
> Update Dependabot GitHub Action

- .github/workflows/docker-hub.yml
- Disable Docker Hub GitHub Action Build on Master
> Disable Docker Hub GitHub Action

- .github/workflows/pypi-publish.yml
- Change branch from `main` to `master`
> Update PyPI Publish GitHub Action

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/dfimage-test.yml
- .github/workflows/docker-hub.yml
- .github/workflows/docker-publish.yml
- Dockerfile
- dfimage.sh
- pyproject.toml
- Update `Dockerfile`
- Update PyPY Project Settings
> Fix GitHub Actions Publish and Test Failures

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .gitignore
- .markdownlint.json
- LICENSE
- README.md
- dfimage.py
- Fix Markdown Issues in All Files
> Fix Markdown Issues
